service: kc-serverless
frameworkVersion: '3'
plugins:
  - serverless-offline-scheduler
  - serverless-offline
provider:
  name: aws
  runtime: nodejs18.x

functions:
  # botsPlayer:
  #   handler: index.run
  #   timeout: 90
  #   events:
  #     # Invoke Lambda function every 2nd minute from Mon-Fri
  #     - schedule: rate(2 minutes)
  logsProcessor:
    handler: chatlogs.run
    url: true
